import { useEffect, useMemo, useState } from "react";
import { BarChart3, Building2, Download, LogOut, RefreshCw, Users, TrendingUp, BookOpen, ChevronRight } from "lucide-react";
import { useNavigate } from "react-router-dom";

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5000/api/v1";

type LearnerRow = { _id:string; learner?:{name:string;email:string;phone?:string}; enrollment?:{status:string;course?:{title:string;technology?:string};batch?:{name:string;startDate?:string;endDate?:string}}; totalLessons:number; completedLessons:number; progressPercentage:number };

export default function CorporatePortal(){
  const navigate=useNavigate(); const [data,setData]=useState<any>(null); const [selected,setSelected]=useState<LearnerRow|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [reporting,setReporting]=useState(false);
  const token=localStorage.getItem("immiq_corporate_token");
  const headers={Authorization:`Bearer ${token||""}`};
  const load=async()=>{try{setLoading(true);setError("");const r=await fetch(`${API_URL}/corporate/dashboard`,{headers});const d=await r.json();if(!r.ok)throw new Error(d.message||"Unable to load corporate portal");setData(d);}catch(e){setError(e instanceof Error?e.message:"Unable to load corporate portal");}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const learners: LearnerRow[]=data?.learners||[];
  const sorted=useMemo(()=>[...learners].sort((a,b)=>b.progressPercentage-a.progressPercentage),[learners]);
  const exportReport=async()=>{try{setReporting(true);const r=await fetch(`${API_URL}/corporate/report`,{headers});const d=await r.json();if(!r.ok)throw new Error(d.message||"Report failed");const rows=d.rows||[];const csv=[Object.keys(rows[0]||{learner:"",email:"",course:"",batch:"",status:"",completedLessons:0,totalLessons:0,progressPercentage:0}).join(","),...rows.map((row:any)=>Object.values(row).map((v:any)=>`"${String(v??"").replaceAll('"','""')}"`).join(","))].join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${(data?.client?.companyName||"immiq-company").replace(/\s+/g,"-").toLowerCase()}-learning-report.csv`;a.click();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:"Unable to export report");}finally{setReporting(false);}};
  const logout=()=>{localStorage.removeItem("immiq_corporate_token");localStorage.removeItem("immiq_corporate_user");navigate("/corporate/login",{replace:true});};
  if(loading)return <main className="min-h-screen bg-slate-950 px-5 py-16 text-white"><div className="mx-auto max-w-7xl animate-pulse"><div className="h-8 w-64 rounded bg-white/10"/><div className="mt-8 grid gap-4 md:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-28 rounded-2xl bg-white/5"/>)}</div></div></main>;
  return <main className="min-h-screen bg-slate-950 px-4 py-6 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
    <header className="flex flex-col gap-4 border-b border-white/10 pb-6 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-cyan-300"><Building2 className="h-5 w-5"/><span className="text-xs font-bold uppercase tracking-[0.25em]">Corporate Learning</span></div><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">{data?.client?.companyName||"Corporate Portal"}</h1><p className="mt-2 text-sm text-slate-400">Track your team’s learning, progress and program completion.</p></div><div className="flex gap-2"><button onClick={load} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-white/10 px-4 text-sm font-bold hover:bg-white/5"><RefreshCw className="h-4 w-4"/>Refresh</button><button onClick={exportReport} disabled={reporting} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-cyan-400 px-4 text-sm font-bold text-slate-950 hover:bg-cyan-300 disabled:opacity-50"><Download className="h-4 w-4"/>{reporting?"Exporting":"Export report"}</button><button onClick={logout} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-white/10 px-4 text-sm font-bold hover:bg-white/5"><LogOut className="h-4 w-4"/>Sign out</button></div></header>
    {error&&<div className="mt-5 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
    <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={<Users/>} label="Assigned learners" value={data?.summary?.totalLearners??0}/><Metric icon={<TrendingUp/>} label="Average progress" value={`${data?.summary?.averageProgress??0}%`}/><Metric icon={<BookOpen/>} label="Active learners" value={data?.summary?.activeLearners??0}/><Metric icon={<BarChart3/>} label="Completed programs" value={data?.summary?.completedPrograms??0}/></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Learner progress</h2><p className="mt-1 text-sm text-slate-400">Program-level visibility across your team.</p></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="border-b border-white/10 text-xs uppercase tracking-wider text-slate-500"><tr><th className="pb-3">Learner</th><th className="pb-3">Program</th><th className="pb-3">Status</th><th className="pb-3">Progress</th><th className="pb-3"></th></tr></thead><tbody>{sorted.map(item=><tr key={item._id} className="border-b border-white/5"><td className="py-4"><div className="font-bold">{item.learner?.name||"Learner"}</div><div className="text-xs text-slate-500">{item.learner?.email}</div></td><td className="py-4 text-sm text-slate-300">{item.enrollment?.course?.title||"-"}</td><td className="py-4"><span className="rounded-full bg-white/5 px-2.5 py-1 text-xs font-bold capitalize">{item.enrollment?.status||"-"}</span></td><td className="py-4"><div className="flex items-center gap-3"><div className="h-2 w-28 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-400" style={{width:`${item.progressPercentage}%`}}/></div><span className="text-sm font-bold">{item.progressPercentage}%</span></div></td><td className="py-4 text-right"><button onClick={()=>setSelected(item)} className="inline-flex items-center gap-1 text-sm font-bold text-cyan-300 hover:text-cyan-200">View <ChevronRight className="h-4 w-4"/></button></td></tr>)}</tbody></table>{sorted.length===0&&<div className="py-14 text-center text-sm text-slate-500">No learners have been assigned yet. Ask your IMMIQ administrator to assign training enrollments.</div>}</div></div>
    <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5 sm:p-6"><h2 className="text-xl font-black">Programs</h2><p className="mt-1 text-sm text-slate-400">Course-wise team performance.</p><div className="mt-5 space-y-4">{(data?.courses||[]).map((course:any)=><div key={course.title} className="rounded-2xl border border-white/10 bg-slate-950/50 p-4"><div className="flex items-center justify-between gap-3"><span className="font-bold">{course.title}</span><span className="text-sm font-black text-cyan-300">{course.averageProgress}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-400" style={{width:`${course.averageProgress}%`}}/></div><p className="mt-2 text-xs text-slate-500">{course.learners} learner{course.learners===1?"":"s"}</p></div>)}{(data?.courses||[]).length===0&&<p className="py-8 text-sm text-slate-500">No programs assigned yet.</p>}</div></div></section>
    {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-0 sm:items-center sm:p-6" onClick={()=>setSelected(null)}><div className="w-full max-w-xl rounded-t-3xl border border-white/10 bg-slate-900 p-6 shadow-2xl sm:rounded-3xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-cyan-300">Learner detail</p><h2 className="mt-1 text-2xl font-black">{selected.learner?.name}</h2><p className="text-sm text-slate-400">{selected.learner?.email}</p></div><button onClick={()=>setSelected(null)} className="rounded-xl border border-white/10 px-3 py-2 text-sm">Close</button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Info label="Program" value={selected.enrollment?.course?.title||"-"}/><Info label="Batch" value={selected.enrollment?.batch?.name||"-"}/><Info label="Lessons" value={`${selected.completedLessons} / ${selected.totalLessons}`}/><Info label="Progress" value={`${selected.progressPercentage}%`}/></div><div className="mt-6 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-400" style={{width:`${selected.progressPercentage}%`}}/></div></div></div>}
  </div></main>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-400/10 text-cyan-300">{icon}</div><p className="mt-4 text-xs uppercase tracking-widest text-slate-500">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs uppercase tracking-widest text-slate-500">{label}</p><p className="mt-1 font-bold text-slate-100">{value}</p></div>}
